download_url: https://node2.aits.my/api/galaxy/v3/plugin/ansible/content/published/collections/artifacts/student-testcollection2-1.2.0.tar.gz
format_version: 1.0.0
name: testcollection2
namespace: student
server: https://node2.aits.my/api/galaxy/content/published/
signatures: []
version: 1.2.0
version_url: /api/galaxy/content/published/v3/plugin/ansible/content/published/collections/index/student/testcollection2/versions/1.2.0/
