download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/paloaltonetworks-panos-2.20.0.tar.gz
format_version: 1.0.0
name: panos
namespace: paloaltonetworks
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.20.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/paloaltonetworks/panos/versions/2.20.0/
