download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/fortinet-fortios-2.3.6.tar.gz
format_version: 1.0.0
name: fortios
namespace: fortinet
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.3.6
version_url: /api/v3/plugin/ansible/content/published/collections/index/fortinet/fortios/versions/2.3.6/
